//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2023 16:30:39
//
//      Input file      : 
//      Component name  : dbncr
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module Dbncr(clk_i, sig_i, pls_o);
   parameter  NR_OF_CLKS = 4095;
   input      clk_i;
   input      sig_i;
   output     pls_o;
   
   
   reg [11:0] cnt;
   reg        sigTmp;
   reg        stble;
   reg        stbleTmp;
   
   
   always @(posedge clk_i)
   begin: DEB
      
      begin
         if (sig_i == sigTmp)
         begin
            if (cnt == NR_OF_CLKS - 1)
               stble <= sig_i;
            else
               cnt <= cnt + 1;
         end
         else
         begin
            cnt <= 0;
            sigTmp <= sig_i;
         end
      end
   end
   
   
   always @(posedge clk_i)
   begin: PLS
      
         stbleTmp <= stble;
   end
   
   assign pls_o = (stbleTmp == 1'b0 & stble == 1'b1) ? 1'b1 : 
                  1'b0;
   
endmodule
