//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2023 16:30:45
//
//      Input file      : 
//      Component name  : ledbar
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module LedBar(clk_i, en_i, rnl_i, leds_o);
   parameter     C_SYS_CLK_FREQ_MHZ = 75;
   parameter     C_SECONDS_TO_RECORD = 3;
   input         clk_i;
   input         en_i;
   input         rnl_i;
   output [15:0] leds_o;
   
   
   parameter     CLK_DIV_RATIO = (((C_SECONDS_TO_RECORD * C_SYS_CLK_FREQ_MHZ * 1000000)/16) - 1);
   
   integer       cnt_clk;
   reg           clk_div;
   reg [15:0]    tmp_sig;
   
   
   always @(posedge clk_i)
   begin: SHFT
      
      begin
         if (en_i == 1'b1)
         begin
            if (clk_div == 1'b1)
            begin
               if (rnl_i == 1'b0)
                  tmp_sig <= {tmp_sig[14:0], 1'b1};
               else
                  tmp_sig <= {1'b1, tmp_sig[15:1]};
            end
         end
         else
            tmp_sig <= {16{1'b0}};
      end
   end
   
   assign leds_o = tmp_sig;
   
   
   always @(posedge clk_i)
   begin: CLK_CNT
      
      begin
         if (en_i == 1'b0 | cnt_clk == CLK_DIV_RATIO)
         begin
            cnt_clk <= 0;
            clk_div <= 1'b1;
         end
         else
         begin
            cnt_clk <= cnt_clk + 1;
            clk_div <= 1'b0;
         end
      end
   end
   
endmodule

