//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2023 16:31:05
//
//      Input file      : 
//      Component name  : nexys4ddruserdemo
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module Nexys4DdrUserDemo(clk_i, rstn_i, btnu_i, sw_i, led_o, pdm_clk_o, pdm_data_i, pdm_lrsel_o, pwm_audio_o, pwm_sdaudio_o, ddr2_addr, ddr2_ba, ddr2_ras_n, ddr2_cas_n, ddr2_we_n, ddr2_ck_p, ddr2_ck_n, ddr2_cke, ddr2_cs_n, ddr2_dm, ddr2_odt, ddr2_dq, ddr2_dqs_p, ddr2_dqs_n);
   input         clk_i;
   input         rstn_i;
   input         btnu_i;
   input [15:0]  sw_i;
   output [15:0] led_o;
   output        pdm_clk_o;
   input         pdm_data_i;
   output        pdm_lrsel_o;
   inout         pwm_audio_o;
   output        pwm_sdaudio_o;
   
   output [12:0] ddr2_addr;
   output [2:0]  ddr2_ba;
   output        ddr2_ras_n;
   output        ddr2_cas_n;
   output        ddr2_we_n;
   output [0:0]  ddr2_ck_p;
   output [0:0]  ddr2_ck_n;
   output [0:0]  ddr2_cke;
   output [0:0]  ddr2_cs_n;
   output [1:0]  ddr2_dm;
   output [0:0]  ddr2_odt;
   inout [15:0]  ddr2_dq;
   inout [1:0]   ddr2_dqs_p;
   inout [1:0]   ddr2_dqs_n;
   
   
   wire          rst;
   wire          reset;
   wire          resetn;
   wire          locked;
   
   wire          clk_100MHz_buf;
   wire          clk_200MHz_buf;
   
   wire [15:0]   led_audio;
   
   wire [11:0]   fpgaTempValue;
   
   wire          pdm_clk;
   wire          pdm_clk_rising;
   
   assign led_o = ((led_audio == 16'h0000)) ? sw_i : 
                  led_audio;
   
   assign rst = (~rstn_i);
   
   assign reset = rst | ((~locked));
   assign resetn = (~reset);
   
   assign pdm_clk_o = pdm_clk;
   
   
   ClkGen Inst_ClkGen(.clk_100MHz_i(clk_i), .clk_100MHz_o(clk_100MHz_buf), .clk_200MHz_o(clk_200MHz_buf), .reset_i(rst), .locked_o(locked));  
   
   AudioDemo Inst_Audio(.clk_200_i(clk_200MHz_buf), .rst_i(reset), .device_temp_i(fpgaTempValue), .btn_u(btnu_i), .leds_o(led_audio), .pdm_m_clk_o(pdm_clk), .pdm_m_data_i(pdm_data_i), .pdm_lrsel_o(pdm_lrsel_o), .pwm_audio_o(pwm_audio_o), .pwm_sdaudio_o(pwm_sdaudio_o), .ddr2_dq(ddr2_dq), .ddr2_dqs_p(ddr2_dqs_p), .ddr2_dqs_n(ddr2_dqs_n), .ddr2_addr(ddr2_addr), .ddr2_ba(ddr2_ba), .ddr2_ras_n(ddr2_ras_n), .ddr2_cas_n(ddr2_cas_n), .ddr2_we_n(ddr2_we_n), .ddr2_ck_p(ddr2_ck_p), .ddr2_ck_n(ddr2_ck_n), .ddr2_cke(ddr2_cke), .ddr2_cs_n(ddr2_cs_n), .ddr2_dm(ddr2_dm), .ddr2_odt(ddr2_odt), .pdm_clk_rising_o(pdm_clk_rising));
   
endmodule


